#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2021 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: LPPL-1.3c

PS4='+ $(date --rfc-3339=seconds), ${BASH_SOURCE-}:${LINENO-}: '
export PS4
trap 'echo Encountered an unexpected error. Exiting with exit code $? in ${BASH_SOURCE-}:${LINENO-}. >&2' ERR
set -o nounset -o pipefail -o errexit -o errtrace


apt-get update
apt-get -y install make chktex lacheck python3
pip3 install git+https://github.com/ypid/reuse-tool.git@add/monorepo-support


make -C doclicense ci
