#!/bin/bash

# SPDX-FileCopyrightText: 2015 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

set -o nounset -o pipefail -o errexit

get() {
    ## https://creativecommons.org/weblog/entry/27094
    modifier="$1"
    version="$2"
    # wget --continue "https://creativecommons.org/licenses/${modifier}/${version}/legalcode" --output-document "doclicense-CC-${modifier}-${version}-latex.html"
    gnuhtml2latex -n "doclicense-CC-${modifier}-${version}-latex.html"

    (
        ## For some stupid reason, LaTeX considers the first % as active or
        ## something and just includes the comment in the document.
        ## The comment environment prevents this.
        echo '\begin{comment}'
        echo '% chktex-file 13 chktex-file 36 chktex-file 38'
        echo '\end{comment}'
        echo
    ) > "doclicense-CC-${modifier}-${version}-latex2.tex"
    ./strip-head-and-tail "doclicense-CC-${modifier}-${version}-latex.tex" | sed --regexp-extended '
        s@\<(https://creativecommons.org/compatiblelicenses|https://creativecommons.org/)@\\url{\1}@ig;
        s/enumerate/doclicense@enumerate/;
    ' | perl -0pe "s/\"(([^\"])*)\"/\`\`\1''/g;s/(Additional languages available):[^.]+/\1/;s/ ,/,/g;" >> "doclicense-CC-${modifier}-${version}-latex2.tex"
    mv "doclicense-CC-${modifier}-${version}-latex2.tex" "doclicense-CC-${modifier}-${version}-latex.tex"
}

get 'zero' '1.0'
get 'by' '3.0'
get 'by-sa' '3.0'
get 'by-nd' '3.0'
get 'by-nc' '3.0'
get 'by-nc-sa' '3.0'
get 'by-nc-nd' '3.0'
get 'by' '4.0'
get 'by-sa' '4.0'
get 'by-nd' '4.0'
get 'by-nc' '4.0'
get 'by-nc-sa' '4.0'
get 'by-nc-nd' '4.0'
