#!/bin/bash
## Copyright (C) 2015 Robin Schneider <ypid@riseup.net>
## SPDX-License-Identifier AGPL-3.0-only

set -o nounset -o pipefail -o errexit

get() {
    ## https://creativecommons.org/weblog/entry/27094
    modifier="$1"
    version="$2"
    wget --continue "https://creativecommons.org/licenses/$modifier/$version/legalcode.txt" --output-document "doclicense-CC-${modifier}-${version}-plaintext.tex"
}

get 'zero' '1.0'
get 'by' '3.0'
get 'by-sa' '3.0'
get 'by-nd' '3.0'
get 'by-nc' '3.0'
get 'by-nc-sa' '3.0'
get 'by-nc-nd' '3.0'
get 'by' '4.0'
get 'by-sa' '4.0'
get 'by-nd' '4.0'
get 'by-nc' '4.0'
get 'by-nc-sa' '4.0'
get 'by-nc-nd' '4.0'
