#!/bin/bash

grep '\\item.*@nameuse{doclicense@lang' ./doclicense.dtx | sed 's/.*\[\([^@]\+\)@\([^]]\+\)\].*/\1 \2/' | while read modifier version; do
# echo 'by 3.0' | while read modifier version; do
# echo 'zero 1.0' | while read modifier version; do
# echo 'pd 1.0' | while read modifier version; do
# echo 'by-nc 3.0' | while read modifier version; do
# echo 'by-nc 4.0' | while read modifier version; do
    for imagemodifier in '' '-us' '-eu'; do
        for lang in 'spanish' 'english' 'ngerman' 'french' 'russian' 'italian' 'polish','dutch'; do
        # for lang in 'spanish'; do
        # for lang in 'english'; do
        # for lang in 'ngerman'; do
        # for lang in 'polish'; do
        # for lang in 'dutch'; do
            if [ "$lang" == "ngerman" ] && [ "$modifier" == "pd" ]; then
                continue # Does not exist in Germany.
            fi
            echo "
                \documentclass[$lang]{article}
                \usepackage{
                    baseRS, %% https://github.com/ypid/typesetting/blob/master/MyPackages/baseRS.sty
                    hyperref,
                    hyperxmp,
                }
                \ifLuaTeX%
                  \setdefaultlanguage{$lang}
                \fi
                \usepackage[
                    type={CC},
                    modifier={$modifier},
                    version={$version},
                    imagemodifier={$imagemodifier},
                ]{doclicense}
                \begin{document}
                doclicenseType
                \doclicenseType%

                doclicenseLongType
                \doclicenseLongType%

                doclicenseModifier
                \doclicenseModifier%

                doclicenseVersion
                \doclicenseVersion%

                doclicenseURL
                \doclicenseURL%

                doclicenseName
                \doclicenseName%

                doclicenseLongName
                \doclicenseLongName%

                doclicenseNameRef
                \doclicenseNameRef%

                doclicenseLongNameRef
                \doclicenseLongNameRef%

                doclicenseText
                \doclicenseText%

                doclicenseLongText
                \doclicenseLongText%

                doclicenseIcon
                \doclicenseIcon%

                doclicenseTypeIcon
                \doclicenseTypeIcon%

                doclicenseImage
                \doclicenseImage%

                doclicenseImageFileName
                \doclicenseImageFileName%

                doclicenseThis
                \doclicenseThis%
                \end{document}" > testing.tex
            latexmk -c
            # lualatex testing.tex
            pdflatex testing.tex
            # break 23
        done
    done
done
