#!/bin/bash

# SPDX-FileCopyrightText: 2015-2022 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

set -o nounset -o pipefail -o errexit

grep '\\item.*@nameuse{doclicense@lang' ./doclicense.dtx | sed 's/.*doclicense@lang@lic@\([^@]\+\)@\([^@]\+\)@\([^]]\+\)}.*/\1 \2 \3/' | sort -u | while read -r type modifier version; do
# echo 'by 3.0' | while read modifier version; do
# echo 'zero 1.0' | while read modifier version; do
# echo 'by-nc 3.0' | while read modifier version; do
# echo 'by-nc 4.0' | while read modifier version; do
    for imagemodifier in "" "-eu" "-80x15"; do
        for lang in "spanish" "english" "ngerman" "french" "russian" "italian" "polish" "portuguese" "catalan" "galician" "croatian" "swedish" "esperanto" "ukrainian"; do
        # for lang in "spanish"; do
        # for lang in "english" "ngerman"; do
        # for lang in "ngerman"; do
        # for lang in "polish"; do
        # for lang in "portuguese"; do
        # for lang in "catalan"; do
        # for lang in "galician"; do
        # for lang in "brazilian"; do
        # for lang in "marathi"; do  ## Has external/new dependencies. Tested manually for now.
        # for lang in "croatian"; do
        # for lang in "swedish"; do
        # for lang in "esperanto"; do
            if [ "$lang" == "ngerman" ] && [ "$modifier" == "pd" ]; then
                continue # Does not exist in Germany.
            fi
            if [ "$imagemodifier" == "-eu" ] && [[ "$modifier" != *-nc-* ]]; then
                continue # eu (Euro) does only exist for nc (non commercial).
            fi

            (

            echo "
                \documentclass[$lang]{article}
                \usepackage{
                    baseRS, %% https://github.com/ypid/typesetting/blob/master/MyPackages/baseRS.sty
                    hyperref,
                    hyperxmp,
                }
                \ifLuaTeX%
                  \setdefaultlanguage{$lang}
                \fi
                \usepackage[
                    type={$type},
                    modifier={$modifier},
                    version={$version},"
            if [ "$imagemodifier" != "" ]; then
                echo "                    imagemodifier={$imagemodifier},% chktex 29"
            fi
            echo "                ]{doclicense}
                \begin{document}
                doclicenseType
                \doclicenseType%

                doclicenseLongType
                \doclicenseLongType%

                doclicenseModifier
                \doclicenseModifier%

                doclicenseVersion
                \doclicenseVersion%

                doclicenseURL
                \doclicenseURL%

                doclicenseName
                \doclicenseName%

                doclicenseLongName
                \doclicenseLongName%

                doclicenseNameRef
                \doclicenseNameRef%

                doclicenseLongNameRef
                \doclicenseLongNameRef%

                doclicenseText
                \doclicenseText%

                doclicenseLongText
                \doclicenseLongText%

                doclicenseIcon
                \doclicenseIcon%

                doclicenseTypeIcon
                \doclicenseTypeIcon%

                doclicenseImage
                \doclicenseImage%

                doclicenseImageFileName
                \doclicenseImageFileName%

                doclicenseThis
                \doclicenseThis%

                doclicensePlainFullText
                \doclicensePlainFullText%

                doclicenseFullText
                \doclicenseFullText%
                \end{document}"

            ) > testing.tex

            echo "*** Testing variant: $lang $type $modifier $version $imagemodifier"

            # latexmk -c
            rm -f testing.aux testing.log testing.out testing.pdf

            # lualatex testing.tex
            # pdflatex -no-shell-escape testing.tex
            pdflatex -no-shell-escape -halt-on-error -interaction=batchmode testing.tex

            # break 23
        done
    done
done
