---
# SPDX-FileCopyrightText: 2021,2023 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: CC0-1.0

name: Continuous Integration

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build docker image
        run: make docker-image
      - name: Lint
        continue-on-error: true
        run: docker-compose run --rm readonly make -C doclicense lint
      - name: Build
        run: docker-compose run --rm readwrite make -C doclicense install-symlink build
      - name: Archive doclicense.pdf
        uses: actions/upload-artifact@v3
        with:
          name: doclicense
          path: doclicense/doclicense.pdf
      - name: test-package-option-matrix-only-english
        run: docker-compose run --rm readwrite make -C doclicense install-symlink test-package-option-matrix-only-english
