---
# SPDX-FileCopyrightText: 2021 Robin Schneider <ypid@riseup.net>
#
# SPDX-License-Identifier: CC0-1.0

name: Continuous Integration
"on":
  - "push"
  - "pull_request"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:

      - name: Set up Git repository
        uses: actions/checkout@v2

      - name: Run CI Makefile target of doclicense package
        uses: xu-cheng/texlive-action/small@v1
        with:
          run: |-
            ./ci_entrypoint
